// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GoSweet.Models
{
    public partial class Customer_datatable
    {
        public int c_number { get; set; }
        public string c_name { get; set; }
        public string c_place { get; set; }
        public string c_phone { get; set; }
        public string c_email { get; set; }

        public virtual Customer_accounttable c_numberNavigation { get; set; }
    }
}