// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace GoSweet.Models
{
    public partial class Customer_accounttable
    {
        public Customer_accounttable()
        {
            Notify_datatables = new HashSet<Notify_datatable>();
            Order_datatables = new HashSet<Order_datatable>();
            Talk_datatables = new HashSet<Talk_datatable>();
            Talk_persontables = new HashSet<Talk_persontable>();
        }

        public string c_nickname { get; set; }
        public int c_number { get; set; }
        [EmailAddress]
        public string c_account { get; set; }
        public string c_password { get; set; }
        public bool c_mailpass { get; set; }

        public Customer_accounttable(string nickname, string account, string password, bool mailpass) { 
            Notify_datatables = new HashSet<Notify_datatable>();
            Order_datatables = new HashSet<Order_datatable>();
            Talk_datatables = new HashSet<Talk_datatable>();
            Talk_persontables = new HashSet<Talk_persontable>();
            c_nickname = nickname;
            c_account = account;
            c_password = password;
            c_mailpass = mailpass;
        }

        public virtual ICollection<Notify_datatable> Notify_datatables { get; set; }
        public virtual ICollection<Order_datatable> Order_datatables { get; set; }
        public virtual ICollection<Talk_datatable> Talk_datatables { get; set; }
        public virtual ICollection<Talk_persontable> Talk_persontables { get; set; }
    }
}