// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GoSweet.Models
{
    public partial class FirmPagetable
    {
        public int FNumber { get; set; }
        public string FPagename { get; set; }
        public string FMessage { get; set; }
        public string FPicurl { get; set; }

        public virtual FirmAccounttable FNumberNavigation { get; set; }
    }
}