// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GoSweet.Models
{
    public partial class Firm_datatable
    {
        public int f_number { get; set; }
        public string f_name { get; set; }
        public string f_place { get; set; }
        public string f_personname { get; set; }
        public string f_mail { get; set; }
        public int? f_tax { get; set; }
        public int? f_phone { get; set; }

        public virtual Firm_accounttable f_numberNavigation { get; set; }
    }
}