// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GoSweet.Models
{
    public partial class Firm_pagetable
    {
        public int f_numberr { get; set; }
        public string f_pagename { get; set; }
        public string f_message { get; set; }

        public virtual Firm_accounttable f_numberrNavigation { get; set; }
    }
}