// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GoSweet.Models
{
    public partial class FirmAccounttable
    {
        public FirmAccounttable()
        {
            GroupDatatables = new HashSet<GroupDatatable>();
            NotifyDatatables = new HashSet<NotifyDatatable>();
            OrderDatatables = new HashSet<OrderDatatable>();
            ProductDatatables = new HashSet<ProductDatatable>();
            TalkDatatables = new HashSet<TalkDatatable>();
            TalkMembertables = new HashSet<TalkMembertable>();
            TalkPersontables = new HashSet<TalkPersontable>();
        }

        public int FNumber { get; set; }
        public string FNickname { get; set; }
        public string FAccount { get; set; }
        public string FPassword { get; set; }
        public bool FMailpass { get; set; }

        public virtual FirmPagetable FirmPagetable { get; set; }
        public virtual ICollection<GroupDatatable> GroupDatatables { get; set; }
        public virtual ICollection<NotifyDatatable> NotifyDatatables { get; set; }
        public virtual ICollection<OrderDatatable> OrderDatatables { get; set; }
        public virtual ICollection<ProductDatatable> ProductDatatables { get; set; }
        public virtual ICollection<TalkDatatable> TalkDatatables { get; set; }
        public virtual ICollection<TalkMembertable> TalkMembertables { get; set; }
        public virtual ICollection<TalkPersontable> TalkPersontables { get; set; }
    }
}