// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;

namespace GoSweet.Models
{
    public partial class Firm_accounttable
    {
        public Firm_accounttable()
        {
            Group_datatables = new HashSet<Group_datatable>();
            Notify_datatables = new HashSet<Notify_datatable>();
            Order_datatables = new HashSet<Order_datatable>();
            Product_datatables = new HashSet<Product_datatable>();
            Talk_datatables = new HashSet<Talk_datatable>();
            Talk_membertables = new HashSet<Talk_membertable>();
            Talk_persontables = new HashSet<Talk_persontable>();
        }

        public int f_number { get; set; }

        [BindProperty(Name = "AccountName")]
        public string f_nickname { get; set; }
        [BindProperty(Name = "UserEmail")]
        public string f_account { get; set; }
        [BindProperty(Name = "UserPassword")]
        public string f_password { get; set; }
        public bool f_mailpass { get; set; }

        public virtual Firm_pagetable Firm_pagetable { get; set; }
        public virtual ICollection<Group_datatable> Group_datatables { get; set; }
        public virtual ICollection<Notify_datatable> Notify_datatables { get; set; }
        public virtual ICollection<Order_datatable> Order_datatables { get; set; }
        public virtual ICollection<Product_datatable> Product_datatables { get; set; }
        public virtual ICollection<Talk_datatable> Talk_datatables { get; set; }
        public virtual ICollection<Talk_membertable> Talk_membertables { get; set; }
        public virtual ICollection<Talk_persontable> Talk_persontables { get; set; }
    }
}