// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GoSweet.Models
{
    public partial class Group_datatable
    {
        public Group_datatable()
        {
            Member_membertables = new HashSet<Member_membertable>();
        }

        public int g_number { get; set; }
        public int f_number { get; set; }
        public int p_number { get; set; }
        public DateTime g_start { get; set; }
        public DateTime g_end { get; set; }
        public int g_maxpeople { get; set; }
        public int g_price { get; set; }

        public virtual Firm_accounttable f_numberNavigation { get; set; }
        public virtual Product_datatable p_numberNavigation { get; set; }
        public virtual ICollection<Member_membertable> Member_membertables { get; set; }
    }
}