// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GoSweet.Models
{
    public partial class GroupDatatable
    {
        public GroupDatatable()
        {
            MemberMembertables = new HashSet<MemberMembertable>();
        }

        public int GNumber { get; set; }
        public int FNumber { get; set; }
        public int PNumber { get; set; }
        public DateTime GStart { get; set; }
        public DateTime GEnd { get; set; }
        public int GMaxpeople { get; set; }
        public int GPrice { get; set; }

        public virtual FirmAccounttable FNumberNavigation { get; set; }
        public virtual ProductDatatable PNumberNavigation { get; set; }
        public virtual ICollection<MemberMembertable> MemberMembertables { get; set; }
    }
}