// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GoSweet.Models
{
    public partial class Lock_datatable
    {
        public int l_number { get; set; }
        public string l_message { get; set; }

        public virtual Firm_accounttable l_number1 { get; set; }
        public virtual Customer_accounttable l_numberNavigation { get; set; }
    }
}