// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GoSweet.Models
{
    public partial class Notify_datatable
    {
        public int n_number { get; set; }
        public int? c_number { get; set; }
        public int? f_number { get; set; }
        public int o_number { get; set; }
        public string o_status { get; set; }
        public bool? n_read { get; set; }

        public virtual Customer_accounttable c_numberNavigation { get; set; }
        public virtual Firm_accounttable f_numberNavigation { get; set; }
        public virtual Order_datatable o_numberNavigation { get; set; }
    }
}