// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GoSweet.Models
{
    public partial class Order_datatable
    {
        public Order_datatable()
        {
            Notify_datatables = new HashSet<Notify_datatable>();
        }

        public int o_number { get; set; }
        public DateTime o_start { get; set; }
        public DateTime? o_end { get; set; }
        public int c_number { get; set; }
        public int f_number { get; set; }
        public bool o_type { get; set; }
        public int? m_number { get; set; }
        public int p_number { get; set; }
        public int o_buynumber { get; set; }
        public int o_price { get; set; }
        public string o_status { get; set; }
        public string o_shipstatus { get; set; }
        public int? o_ship { get; set; }
        public string o_place { get; set; }
        public int? o_payment { get; set; }

        public virtual Customer_accounttable c_numberNavigation { get; set; }
        public virtual Firm_accounttable f_numberNavigation { get; set; }
        public virtual Member_membertable m_numberNavigation { get; set; }
        public virtual Payment_datatable o_paymentNavigation { get; set; }
        public virtual Ship_datatable o_shipNavigation { get; set; }
        public virtual Product_datatable p_numberNavigation { get; set; }
        public virtual Order_assesstable Order_assesstable { get; set; }
        public virtual ICollection<Notify_datatable> Notify_datatables { get; set; }
    }
}