// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GoSweet.Models
{
    public partial class OrderDatatable
    {
        public OrderDatatable()
        {
            NotifyDatatables = new HashSet<NotifyDatatable>();
        }

        public int ONumber { get; set; }
        public DateTime OStart { get; set; }
        public DateTime? OEnd { get; set; }
        public int CNumber { get; set; }
        public int FNumber { get; set; }
        public bool OType { get; set; }
        public int? MNumber { get; set; }
        public int PNumber { get; set; }
        public int OBuynumber { get; set; }
        public int OPrice { get; set; }
        public string OStatus { get; set; }
        public string OShipstatus { get; set; }
        public int? OShip { get; set; }
        public string OPlace { get; set; }
        public int? OPayment { get; set; }

        public virtual CustomerAccounttable CNumberNavigation { get; set; }
        public virtual FirmAccounttable FNumberNavigation { get; set; }
        public virtual MemberMembertable MNumberNavigation { get; set; }
        public virtual PaymentDatatable OPaymentNavigation { get; set; }
        public virtual ShipDatatable OShipNavigation { get; set; }
        public virtual ProductDatatable PNumberNavigation { get; set; }
        public virtual OrderAssesstable OrderAssesstable { get; set; }
        public virtual ICollection<NotifyDatatable> NotifyDatatables { get; set; }
    }
}