// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GoSweet.Models
{
    public partial class Order_assesstable
    {
        public int o_number { get; set; }
        public double? o_cscore { get; set; }
        public string o_ccomment { get; set; }
        public double? o_fscore { get; set; }
        public string o_fcomment { get; set; }

        public virtual Order_datatable o_numberNavigation { get; set; }
    }
}