// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GoSweet.Models
{
    public partial class Product_datatable
    {
        public Product_datatable()
        {
            Group_datatables = new HashSet<Group_datatable>();
            Order_assesstables = new HashSet<Order_assesstable>();
            Order_datatables = new HashSet<Order_datatable>();
            Product_picturetables = new HashSet<Product_picturetable>();
            Payment_numbers = new HashSet<Payment_datatable>();
            ship_numbers = new HashSet<Ship_datatable>();
        }

        public int f_number { get; set; }
        public int p_number { get; set; }
        public string p_name { get; set; }
        public string p_spec { get; set; }
        public string p_category { get; set; }
        public int p_price { get; set; }
        public string p_describe { get; set; }
        public string p_savedate { get; set; }
        public string p_saveway { get; set; }
        public int p_Inventory { get; set; }
        public int? p_ship { get; set; }
        public int? p_payment { get; set; }

        public virtual Firm_accounttable f_numberNavigation { get; set; }
        public virtual ICollection<Group_datatable> Group_datatables { get; set; }
        public virtual ICollection<Order_assesstable> Order_assesstables { get; set; }
        public virtual ICollection<Order_datatable> Order_datatables { get; set; }
        public virtual ICollection<Product_picturetable> Product_picturetables { get; set; }

        public virtual ICollection<Payment_datatable> Payment_numbers { get; set; }
        public virtual ICollection<Ship_datatable> ship_numbers { get; set; }
    }
}