// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GoSweet.Models
{
    public partial class ShipDatatable
    {
        public ShipDatatable()
        {
            OrderDatatables = new HashSet<OrderDatatable>();
            PNumbers = new HashSet<ProductDatatable>();
        }

        public int ShipNumber { get; set; }
        public string ShipName { get; set; }

        public virtual ICollection<OrderDatatable> OrderDatatables { get; set; }

        public virtual ICollection<ProductDatatable> PNumbers { get; set; }
    }
}