// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GoSweet.Models
{
    public partial class Talk_membertable
    {
        public int Talk_member_id { get; set; }
        public int c_number { get; set; }
        public int f_number { get; set; }

        public virtual Customer_accounttable c_numberNavigation { get; set; }
        public virtual Firm_accounttable f_numberNavigation { get; set; }
    }
}