// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GoSweet.Models
{
    public partial class TalkDatatable
    {
        public int TNumber { get; set; }
        public int CNumber { get; set; }
        public int FNumber { get; set; }
        public DateTime TTime { get; set; }
        public string TMessage { get; set; }
        public int TRead { get; set; }
        public int TPost { get; set; }

        public virtual CustomerAccounttable CNumberNavigation { get; set; }
        public virtual FirmAccounttable FNumberNavigation { get; set; }
    }
}