// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CRUDExample.Models
{
    public partial class Address_All
    {
        public int id { get; set; }
        public string city_name { get; set; }
        public string district_name { get; set; }
        public string street_name { get; set; }
    }
}