// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CRUDExample.Models
{
    public partial class Address_3
    {
        public int a3_id { get; set; }
        public int a1_id { get; set; }
        public int a2_id { get; set; }
        public string street_name { get; set; }
    }
}