// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CRUDExample.Models
{
    public partial class aspnet_Application
    {
        public aspnet_Application()
        {
            aspnet_Memberships = new HashSet<aspnet_Membership>();
            aspnet_Paths = new HashSet<aspnet_Path>();
            aspnet_Roles = new HashSet<aspnet_Role>();
            aspnet_Users = new HashSet<aspnet_User>();
        }

        public string ApplicationName { get; set; }
        public string LoweredApplicationName { get; set; }
        public Guid ApplicationId { get; set; }
        public string Description { get; set; }

        public virtual ICollection<aspnet_Membership> aspnet_Memberships { get; set; }
        public virtual ICollection<aspnet_Path> aspnet_Paths { get; set; }
        public virtual ICollection<aspnet_Role> aspnet_Roles { get; set; }
        public virtual ICollection<aspnet_User> aspnet_Users { get; set; }
    }
}