// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CRUDExample.Models
{
    public partial class AspNet_SqlCacheTablesForChangeNotification
    {
        public string tableName { get; set; }
        public DateTime notificationCreated { get; set; }
        public int changeId { get; set; }
    }
}