// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CRUDExample.Models
{
    public partial class aspnet_Role
    {
        public aspnet_Role()
        {
            Users = new HashSet<aspnet_User>();
        }

        public Guid ApplicationId { get; set; }
        public Guid RoleId { get; set; }
        public string RoleName { get; set; }
        public string LoweredRoleName { get; set; }
        public string Description { get; set; }

        public virtual aspnet_Application Application { get; set; }

        public virtual ICollection<aspnet_User> Users { get; set; }
    }
}