// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CRUDExample.Models
{
    public partial class Calendar_Schedule
    {
        public int CS_id { get; set; }
        public DateTime CS_time { get; set; }
        public string CS_title { get; set; }
        public string CS_summary { get; set; }
    }
}