// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CRUDExample.Models
{
    public partial class db_user
    {
        public int id { get; set; }
        public string real_name { get; set; }
        public string name { get; set; }
        public string password { get; set; }
        public string sex { get; set; }
        public string email { get; set; }
        public int rank { get; set; }
        public string UpdateRight { get; set; }
        public string DeleteRight { get; set; }
    }
}