// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CRUDExample.Models
{
    public partial class Drink_Product
    {
        public int id { get; set; }
        public string drink_class { get; set; }
        public string drink_name { get; set; }
        public int? drink_price { get; set; }
        public int? drink_cost { get; set; }
    }
}