// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CRUDExample.Models
{
    public partial class Drink_Order_M
    {
        public int id { get; set; }
        public DateTime? order_time { get; set; }
        public string user_name { get; set; }
        public string user_phone { get; set; }
        public string memo { get; set; }
        public string have_paid { get; set; }
    }
}