// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CRUDExample.Models
{
    public partial class Drink_Order_D
    {
        public int id { get; set; }
        public int order_id { get; set; }
        public int? drink_id { get; set; }
        public string drink_name { get; set; }
        public string ice_degree { get; set; }
        public string sweet_degree { get; set; }
        public int? drink_no { get; set; }
        public string meno { get; set; }
        public string approved { get; set; }
    }
}