// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CRUDExample.Models
{
    public partial class FileUpload_DB
    {
        public int FileUpload_DB_id { get; set; }
        public DateTime? FileUpload_time { get; set; }
        public int test_id { get; set; }
        public string FileUpload_FileName { get; set; }
        public string FileUpload_Memo { get; set; }
        public string FileUpload_User { get; set; }
    }
}