// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CRUDExample.Models
{
    public partial class Food_Menu
    {
        public int id { get; set; }
        public string food_class { get; set; }
        public string food_name { get; set; }
    }
}