// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CRUDExample.Models
{
    public partial class Food_Calorie
    {
        public int id { get; set; }
        public string food_name { get; set; }
        public string food_unit { get; set; }
        public int? food_Calorie1 { get; set; }
    }
}