// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CRUDExample.Models
{
    public partial class News_Test_Class
    {
        public int Test_Class_id { get; set; }
        public string test_class { get; set; }
        public string test_class_1 { get; set; }
        public string test_class_2 { get; set; }
    }
}