// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CRUDExample.Models
{
    public partial class News_Test_Talk
    {
        public int test_talk_id { get; set; }
        public int test_id { get; set; }
        public DateTime? test_time { get; set; }
        public string article { get; set; }
        public string author { get; set; }
        public string email { get; set; }
    }
}