// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CRUDExample.Models
{
    public partial class News_User
    {
        public int User_id { get; set; }
        public string User_Real_Name { get; set; }
        public string User_Account { get; set; }
        public string User_Password { get; set; }
        public int User_Rank { get; set; }
        public string User_email { get; set; }
    }
}