// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CRUDExample.Models
{
    public partial class News_Test
    {
        public int test_id { get; set; }
        public Guid? test_guid { get; set; }
        public DateTime? test_time { get; set; }
        public string test_class { get; set; }
        public string title { get; set; }
        public string summary { get; set; }
        public string article { get; set; }
        public string author { get; set; }
        public int hit_no { get; set; }
        public int get_no { get; set; }
        public int email_no { get; set; }
        public string approved { get; set; }
    }
}