// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CRUDExample.Models
{
    public partial class Question_M
    {
        public int M_id { get; set; }
        public string M_title { get; set; }
        public DateTime? start_time { get; set; }
        public DateTime? end_time { get; set; }
        public string M_summary { get; set; }
        public string M_enable { get; set; }
    }
}