// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CRUDExample.Models
{
    public partial class Question_D1
    {
        public int D1_id { get; set; }
        public int M_id { get; set; }
        public string D1_title { get; set; }
        public string D1_summary { get; set; }
        public string D1_type { get; set; }
        public string D1_mustKeyin { get; set; }
    }
}