// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CRUDExample.Models
{
    public partial class student_department
    {
        public int sd_id { get; set; }
        public string student_department1 { get; set; }
        public string department_leader { get; set; }
    }
}