// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel;

namespace CRUDExample.Models
{
    public partial class student_test
    {
        [DisplayName("id")]
        public int id { get; set; }
        [DisplayName("name")]
        public string name { get; set; }
        [DisplayName("student_id")]
        public string student_id { get; set; }
        [DisplayName("city")]
        public string city { get; set; }
        [DisplayName("chinese")]
        public int? chinese { get; set; }
        [DisplayName("math")]
        public int? math { get; set; }
    }
}