// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CRUDExample.Models
{
    public partial class student_class
    {
        public string student_id { get; set; }
        public int sd_id { get; set; }
        public int? student_year { get; set; }
        public string student_class1 { get; set; }
    }
}