// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CRUDExample.Models
{
    public partial class test_only
    {
        public int test_no { get; set; }
        public string test_title { get; set; }
        public long test_id { get; set; }
    }
}