// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CRUDExample.Models
{
    public partial class test
    {
        public int id { get; set; }
        public DateTime? test_time { get; set; }
        public string _class { get; set; }
        public string title { get; set; }
        public string summary { get; set; }
        public string article { get; set; }
        public string author { get; set; }
        public int? hit_no { get; set; }
        public int? get_no { get; set; }
        public int? email_no { get; set; }
        public string approved { get; set; }
    }
}