// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CRUDExample.Models
{
    public partial class test_class
    {
        public int test_class_id { get; set; }
        public string test_class1 { get; set; }
        public string test_class11 { get; set; }
        public string test_class2 { get; set; }
    }
}