// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CRUDExample.Models
{
    public partial class test1
    {
        public int id { get; set; }
        public string test { get; set; }
        public byte[] time_st { get; set; }
    }
}