// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CRUDExample.Models
{
    public partial class test_timestamp
    {
        public int id { get; set; }
        public string title { get; set; }
        public DateTime? test_time { get; set; }
        public byte[] test_TS { get; set; }
    }
}