// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CRUDExample.Models
{
    public partial class test_ad
    {
        public int ad_id { get; set; }
        public DateTime? ad_time_start { get; set; }
        public DateTime? ad_time_end { get; set; }
        public string ad_images { get; set; }
        public string ad_url { get; set; }
    }
}