// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CRUDExample.Models
{
    public partial class Vote_Auto
    {
        public int vote_id { get; set; }
        public DateTime? Vote_time { get; set; }
        public string title { get; set; }
        public string question_1 { get; set; }
        public int answer_1 { get; set; }
        public string question_2 { get; set; }
        public int answer_2 { get; set; }
        public string question_3 { get; set; }
        public int answer_3 { get; set; }
        public string question_4 { get; set; }
        public int answer_4 { get; set; }
        public string question_5 { get; set; }
        public int answer_5 { get; set; }
        public string question_6 { get; set; }
        public int answer_6 { get; set; }
        public string question_7 { get; set; }
        public int answer_7 { get; set; }
        public string question_8 { get; set; }
        public int answer_8 { get; set; }
        public string question_9 { get; set; }
        public int answer_9 { get; set; }
        public string question_10 { get; set; }
        public int answer_10 { get; set; }
        public int question_all { get; set; }
    }
}