// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CRUDExample.Models
{
    public partial class Vote_1
    {
        public int id { get; set; }
        public int vote_11 { get; set; }
        public int vote_2 { get; set; }
        public int vote_3 { get; set; }
        public int vote_4 { get; set; }
        public int vote_5 { get; set; }
        public int vote_6 { get; set; }
    }
}