// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CRUDExample.Models
{
    public partial class Vote_2
    {
        public int id { get; set; }
        public int? vote_id { get; set; }
        public DateTime? vote_date { get; set; }
        public string vote_to { get; set; }
        public string vote_ip { get; set; }
    }
}